services:
  kanban-app:
    build:
      context: ./estoNoEsTrello
      dockerfile: Dockerfile
    container_name: nova_kanban_app
    ports:
      - "8080:8080"
    volumes:
      - ./estoNoEsTrello/src/main/resources/JSONs:/app/JSONs
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
